Fixing error when using Mongomock with mongoengine documents.
The error occurs when using a UUIDField(binary=True) field.

The stack fails with:
File "/home/jenkins/src/mongomock/mongomock/collection.py", line 505, in _insert
    BSON.encode(data, check_keys=True)
  File "/home/jenkins/.local/lib/python3.8/site-packages/bson/__init__.py", line 1353, in encode
    return cls(encode(document, check_keys, codec_options))
  File "/home/jenkins/.local/lib/python3.8/site-packages/bson/__init__.py", line 1021, in encode
    return _dict_to_bson(document, check_keys, codec_options)
  File "/home/jenkins/.local/lib/python3.8/site-packages/bson/binary.py", line 267, in from_uuid
    raise ValueError(
ValueError: cannot encode native uuid.UUID with UuidRepresentation.UNSPECIFIED. UUIDs can be manually converted to bson.Binary instances using bson.Binary.from_uuid() or a different UuidRepresentation can be configured. See the documentation for UuidRepresentation for more information.